# Staging Profile (staging)
spring:
  config:
    activate:
      on-profile: staging

tamva:
  seeder:
    enabled: false

logging:
  level:
    com.tamvagbackend: INFO
    org.springframework.security: INFO
